### ISSUE TITLE
Account Decoder within yaml schema

### ISSUE THREAD

**Issue by ghabxph** [ghabxph/yaml2solana#33]
Implement ability to decode account from yaml.

Sample use case:

```yaml
pda:
  somePda:
    programId: $SOME_PROGRAM
    seeds:
      - seed-string
      - somePda.value1
      - somePda.value2
  
schemaDefinition:
  SomePda:
    - discriminator(SomePda)
    - $value1:pubkey
    - $value2:pubkey
```
